apiVersion: v1
kind: Secret
metadata:
  name: fnfgngnfgnfgn-secret
  namespace: fnfgngnfgnfgn
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
